# Generated by Django 4.2.2 on 2023-09-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlitterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("strike_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.IntegerField()),
                ("expiration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TableModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("strike_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.IntegerField()),
                ("expiration_date", models.DateField()),
            ],
        ),
    ]
